/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9s23dw65yRdJrLkTBtT6tX

import * as React from "react";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 9s23dw65yRdJrLkTBtT6tX/projectModule
import { EmbedCss } from "@plasmicpkgs/plasmic-embed-css";

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  embedCssProps?: Partial<
    Omit<React.ComponentProps<typeof EmbedCss>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, embedCssProps } = props;

  return (
    <EmbedCss
      {...embedCssProps}
      css={
        embedCssProps && "css" in embedCssProps
          ? embedCssProps.css!
          : "/* CSS snippet */\n\n.pattern-bg {\n    background-image: url(\"data:image/svg+xml;utf8,<svg width='6' height='6' viewBox='0 0 6 6' xmlns='http://www.w3.org/2000/svg'><circle cx='1.55469' cy='1.11719' r='1' fill='black' fill-opacity='0.25'/><rect x='3.55469' y='0.117188' width='2' height='2' fill='black' fill-opacity='0.25'/><path d='M2.05469 3.61719H2.55469V4.61719H2.05469V5.11719H1.05469V4.61719H0.554688V3.61719H1.05469V3.11719H2.05469V3.61719Z' fill='black' fill-opacity='0.25'/><circle cx='4.55469' cy='4.11719' r='1' fill='black' fill-opacity='0.25'/></svg>\");\n    background-repeat: repeat;\n    background-size: 7px 7px;\n}\n\n.pattern-w-bg {\n    background-image: url(\"data:image/svg+xml;utf8,<svg width='3' height='3' viewBox='0 0 3 3' fill='none' xmlns='http://www.w3.org/2000/svg'><g clip-path='url(%23clip0_351_1849)'><circle cx='1.9624' cy='1.22095' r='1' fill='white' fill-opacity='0.35'/></g><defs><clipPath id='clip0_351_1849'><rect width='3' height='3' fill='white' transform='translate(0.962402 0.220947)'/></clipPath></defs></svg>\");\n    background-repeat: repeat;\n    background-size: 3px 3px;\n}\n\n.article-2w{\n  width: calc(50% - 10px);\n}\n\n\n\n\n"
      }
    >
      {children}
    </EmbedCss>
  );
}
