/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9s23dw65yRdJrLkTBtT6tX
// Component: pEihuiYxuX

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 9s23dw65yRdJrLkTBtT6tX/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 9s23dw65yRdJrLkTBtT6tX/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 9s23dw65yRdJrLkTBtT6tX/projectcss
import sty from "./PlasmicHeader.module.css"; // plasmic-import: pEihuiYxuX/css

import Group1Icon from "./icons/PlasmicIcon__Group1"; // plasmic-import: G4-ZuWH_R/icon

createPlasmicElementProxy;

export type PlasmicHeader__VariantMembers = {};
export type PlasmicHeader__VariantsArgs = {};
type VariantPropType = keyof PlasmicHeader__VariantsArgs;
export const PlasmicHeader__VariantProps = new Array<VariantPropType>();

export type PlasmicHeader__ArgsType = {};
type ArgPropType = keyof PlasmicHeader__ArgsType;
export const PlasmicHeader__ArgProps = new Array<ArgPropType>();

export type PlasmicHeader__OverridesType = {
  root?: Flex__<"div">;
  group24?: Flex__<"div">;
  frame1?: Flex__<"div">;
  святогаАпостала?: Flex__<"div">;
  frame2?: Flex__<"div">;
  vilniusUzupioG17A?: Flex__<"div">;
  svg?: Flex__<"svg">;
};

export interface DefaultHeaderProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHeader__RenderFunc(props: {
  variants: PlasmicHeader__VariantsArgs;
  args: PlasmicHeader__ArgsType;
  overrides: PlasmicHeader__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        {
          [sty.rootglobal_color_black]: hasVariant(
            globalVariants,
            "color",
            "black"
          ),
          [sty.rootglobal_color_gold]: hasVariant(
            globalVariants,
            "color",
            "gold"
          ),
          [sty.rootglobal_color_normal]: hasVariant(
            globalVariants,
            "color",
            "normal"
          ),
          [sty.rootglobal_color_pink]: hasVariant(
            globalVariants,
            "color",
            "pink"
          ),
          [sty.rootglobal_color_purple]: hasVariant(
            globalVariants,
            "color",
            "purple"
          ),
          [sty.rootglobal_color_red]: hasVariant(globalVariants, "color", "red")
        }
      )}
    >
      <div
        data-plasmic-name={"group24"}
        data-plasmic-override={overrides.group24}
        className={classNames(projectcss.all, sty.group24, {
          [sty.group24global_color_normal]: hasVariant(
            globalVariants,
            "color",
            "normal"
          )
        })}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__bdrB5
          )}
        >
          {"\u0411\u0430\u0440\u0442\u0430\u043b\u0430\u043c\u0435\u044f"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___3U1Jt,
            {
              [sty.textglobal_color_purple___3U1JtW4Da]: hasVariant(
                globalVariants,
                "color",
                "purple"
              )
            }
          )}
        >
          {"\u043f\u0430\u0440\u0430\u0444\u0456\u044f"}
        </div>
        <div
          data-plasmic-name={"frame1"}
          data-plasmic-override={overrides.frame1}
          className={classNames(projectcss.all, sty.frame1)}
        >
          <div
            data-plasmic-name={
              "\u0441\u0432\u044f\u0442\u043e\u0433\u0430\u0410\u043f\u043e\u0441\u0442\u0430\u043b\u0430"
            }
            data-plasmic-override={overrides.святогаАпостала}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.святогаапостала
            )}
          >
            {
              "\u0441\u0432\u044f\u0442\u043e\u0433\u0430 \u0430\u043f\u043e\u0441\u0442\u0430\u043b\u0430 "
            }
          </div>
        </div>
        <div
          data-plasmic-name={"frame2"}
          data-plasmic-override={overrides.frame2}
          className={classNames(projectcss.all, sty.frame2)}
        >
          <div
            data-plasmic-name={"vilniusUzupioG17A"}
            data-plasmic-override={overrides.vilniusUzupioG17A}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.vilniusUzupioG17A
            )}
          >
            {"Vilnius, U\u017eupio g. 17A  "}
          </div>
        </div>
        <Group1Icon
          data-plasmic-name={"svg"}
          data-plasmic-override={overrides.svg}
          className={classNames(projectcss.all, sty.svg)}
          role={"img"}
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "group24",
    "frame1",
    "\u0441\u0432\u044f\u0442\u043e\u0433\u0430\u0410\u043f\u043e\u0441\u0442\u0430\u043b\u0430",
    "frame2",
    "vilniusUzupioG17A",
    "svg"
  ],
  group24: [
    "group24",
    "frame1",
    "\u0441\u0432\u044f\u0442\u043e\u0433\u0430\u0410\u043f\u043e\u0441\u0442\u0430\u043b\u0430",
    "frame2",
    "vilniusUzupioG17A",
    "svg"
  ],
  frame1: [
    "frame1",
    "\u0441\u0432\u044f\u0442\u043e\u0433\u0430\u0410\u043f\u043e\u0441\u0442\u0430\u043b\u0430"
  ],
  святогаАпостала: [
    "\u0441\u0432\u044f\u0442\u043e\u0433\u0430\u0410\u043f\u043e\u0441\u0442\u0430\u043b\u0430"
  ],
  frame2: ["frame2", "vilniusUzupioG17A"],
  vilniusUzupioG17A: ["vilniusUzupioG17A"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  group24: "div";
  frame1: "div";
  святогаАпостала: "div";
  frame2: "div";
  vilniusUzupioG17A: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHeader__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHeader__VariantsArgs;
    args?: PlasmicHeader__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHeader__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHeader__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHeader__ArgProps,
          internalVariantPropNames: PlasmicHeader__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHeader";
  } else {
    func.displayName = `PlasmicHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicHeader = Object.assign(
  // Top-level PlasmicHeader renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    group24: makeNodeComponent("group24"),
    frame1: makeNodeComponent("frame1"),
    святогаАпостала: makeNodeComponent(
      "\u0441\u0432\u044f\u0442\u043e\u0433\u0430\u0410\u043f\u043e\u0441\u0442\u0430\u043b\u0430"
    ),
    frame2: makeNodeComponent("frame2"),
    vilniusUzupioG17A: makeNodeComponent("vilniusUzupioG17A"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicHeader
    internalVariantProps: PlasmicHeader__VariantProps,
    internalArgProps: PlasmicHeader__ArgProps
  }
);

export default PlasmicHeader;
/* prettier-ignore-end */
