/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9s23dw65yRdJrLkTBtT6tX

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 9s23dw65yRdJrLkTBtT6tX/projectModule

import projectcss from "./plasmic.module.css"; // plasmic-import: 9s23dw65yRdJrLkTBtT6tX/projectcss

const data = {
  base: `${projectcss.plasmic_tokens}`,
  varianted: [
    {
      className: projectcss.global_color_purple,
      groupName: "color",
      variant: "purple"
    },
    {
      className: projectcss.global_color_red,
      groupName: "color",
      variant: "red"
    },
    {
      className: projectcss.global_color_black,
      groupName: "color",
      variant: "black"
    },
    {
      className: projectcss.global_color_pink,
      groupName: "color",
      variant: "pink"
    },
    {
      className: projectcss.global_color_gold,
      groupName: "color",
      variant: "gold"
    }
  ]
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
