/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9s23dw65yRdJrLkTBtT6tX
// Component: 1GAgFXuVa4BD

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 9s23dw65yRdJrLkTBtT6tX/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 9s23dw65yRdJrLkTBtT6tX/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 9s23dw65yRdJrLkTBtT6tX/projectcss
import sty from "./PlasmicAnonce.module.css"; // plasmic-import: 1GAgFXuVa4BD/css

import Frame86Icon from "./icons/PlasmicIcon__Frame86"; // plasmic-import: ndXafDPbeH_t/icon

createPlasmicElementProxy;

export type PlasmicAnonce__VariantMembers = {
  noLink: "noLink";
};
export type PlasmicAnonce__VariantsArgs = {
  noLink?: SingleBooleanChoiceArg<"noLink">;
};
type VariantPropType = keyof PlasmicAnonce__VariantsArgs;
export const PlasmicAnonce__VariantProps = new Array<VariantPropType>("noLink");

export type PlasmicAnonce__ArgsType = {
  tilte?: string;
  descrption?: string;
  destination?: string;
  link?: boolean;
  ешеду?: React.ReactNode;
  children?: React.ReactNode;
};
type ArgPropType = keyof PlasmicAnonce__ArgsType;
export const PlasmicAnonce__ArgProps = new Array<ArgPropType>(
  "tilte",
  "descrption",
  "destination",
  "link",
  "\u0435\u0448\u0435\u0434\u0443",
  "children"
);

export type PlasmicAnonce__OverridesType = {
  frame82?: Flex__<"a"> & Partial<LinkProps>;
  frame85?: Flex__<"div">;
  svg?: Flex__<"svg">;
};

export interface DefaultAnonceProps {
  tilte?: string;
  descrption?: string;
  destination?: string;
  link?: boolean;
  ешеду?: React.ReactNode;
  children?: React.ReactNode;
  noLink?: SingleBooleanChoiceArg<"noLink">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAnonce__RenderFunc(props: {
  variants: PlasmicAnonce__VariantsArgs;
  args: PlasmicAnonce__ArgsType;
  overrides: PlasmicAnonce__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          tilte: "\u0417\u0430\u0433\u0430\u043b\u043e\u0432\u0430\u043a",
          descrption:
            "\u0428\u0442\u043e\u0441\u0446\u0456 \u0446\u0456\u043a\u0430\u0432\u0430\u0435: \u0430\u043b\u0435 \u043a\u0430\u0440\u043e\u0442\u043a\u0430\u0435",
          link: false
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "noLink",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.noLink
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <PlasmicLink__
      data-plasmic-name={"frame82"}
      data-plasmic-override={overrides.frame82}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.a,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.frame82
      )}
      component={Link}
      href={args.destination}
      platform={"nextjs"}
    >
      <div
        data-plasmic-name={"frame85"}
        data-plasmic-override={overrides.frame85}
        className={classNames(projectcss.all, sty.frame85)}
      >
        <div className={classNames(projectcss.all, sty.freeBox__q5Jiv)}>
          {renderPlasmicSlot({
            defaultContents:
              "\u0420\u0443\u0436\u0430\u043d\u0446\u043e\u0432\u044b\u044f \u043c\u0430\u043b\u0456\u0442\u0432\u044b",
            value: args.ешеду,
            className: classNames(sty.slotTargetешеду)
          })}
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__kZlTy)}>
          {renderPlasmicSlot({
            defaultContents:
              "\u0422\u0440\u044b\u0432\u0430\u0435 \u043c\u0435\u0441\u044f\u0446 \u043a\u0430\u0441\u0442\u0440\u044b\u0447\u043d\u0456\u043a, \u0443 \u044f\u043a\u0456\u043c \u0430\u0441\u0430\u0431\u043b\u0456\u0432\u044b\u043c \u0447\u044b\u043d\u0430\u043c \u043c\u0430\u043b\u0456\u043c\u0441\u044f \u043d\u0430 \u0420\u0443\u0436\u0430\u043d\u0446\u044b.\u00a0\u0417\u0430\u043f\u0440\u0430\u0448\u0430\u0435\u043c \u043d\u0430 \u0440\u0443\u0436\u0430\u043d\u0446\u043e\u0432\u044b\u044f \u043d\u0430\u0431\u0430\u0436\u044d\u043d\u0441\u0442\u0432\u044b",
            value: args.children,
            className: classNames(sty.slotTargetChildren)
          })}
        </div>
        <Frame86Icon
          data-plasmic-name={"svg"}
          data-plasmic-override={overrides.svg}
          className={classNames(projectcss.all, sty.svg, {
            [sty.svgnoLink]: hasVariant($state, "noLink", "noLink")
          })}
          role={"img"}
        />
      </div>
    </PlasmicLink__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  frame82: ["frame82", "frame85", "svg"],
  frame85: ["frame85", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  frame82: "a";
  frame85: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAnonce__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAnonce__VariantsArgs;
    args?: PlasmicAnonce__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicAnonce__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicAnonce__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAnonce__ArgProps,
          internalVariantPropNames: PlasmicAnonce__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAnonce__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "frame82") {
    func.displayName = "PlasmicAnonce";
  } else {
    func.displayName = `PlasmicAnonce.${nodeName}`;
  }
  return func;
}

export const PlasmicAnonce = Object.assign(
  // Top-level PlasmicAnonce renders the root element
  makeNodeComponent("frame82"),
  {
    // Helper components rendering sub-elements
    frame85: makeNodeComponent("frame85"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicAnonce
    internalVariantProps: PlasmicAnonce__VariantProps,
    internalArgProps: PlasmicAnonce__ArgProps
  }
);

export default PlasmicAnonce;
/* prettier-ignore-end */
