/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9s23dw65yRdJrLkTBtT6tX

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantslCfJywSArQOzV } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: lCFJywSArQOzV/globalVariant
import { ColorValue, useColor } from "./PlasmicGlobalVariant__Color"; // plasmic-import: ALafhAQAXP/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantslCfJywSArQOzV,
  color: useColor
});
