/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9s23dw65yRdJrLkTBtT6tX
// Component: VhGs5g5Pr3ZL

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 9s23dw65yRdJrLkTBtT6tX/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 9s23dw65yRdJrLkTBtT6tX/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 9s23dw65yRdJrLkTBtT6tX/projectcss
import sty from "./PlasmicHome.module.css"; // plasmic-import: VhGs5g5Pr3ZL/css

createPlasmicElementProxy;

export type PlasmicHome__VariantMembers = {};
export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>();

export type PlasmicHome__OverridesType = {
  root?: Flex__<"div">;
  link?: Flex__<"a"> & Partial<LinkProps>;
  frame92?: Flex__<"div">;
};

export interface DefaultHomeProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__zRJdX)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__kDZvB)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/baltramiejus/images/image5.svg",
                fullWidth: 691,
                fullHeight: 468,
                aspectRatio: undefined
              }}
            />

            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__kt5T8)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/baltramiejus/images/image7.svg",
                fullWidth: 249,
                fullHeight: 52,
                aspectRatio: undefined
              }}
            />

            <PlasmicLink__
              data-plasmic-name={"link"}
              data-plasmic-override={overrides.link}
              className={classNames(projectcss.all, projectcss.a, sty.link)}
              component={Link}
              href={`/abjavy?%3Flang%3Dby=${``}`}
              platform={"nextjs"}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__l2O3R)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "none"
                    : "100%"
                }
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "537px"
                    : "auto"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/baltramiejus/images/image6.svg",
                  fullWidth: 647,
                  fullHeight: 114,
                  aspectRatio: undefined
                }}
              />
            </PlasmicLink__>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img___3V7F)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/baltramiejus/images/image8.svg",
                fullWidth: 460,
                fullHeight: 247,
                aspectRatio: undefined
              }}
            />

            <PlasmicImg__
              alt={""}
              className={classNames(sty.img___6RIk)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"none"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/baltramiejus/images/image9.svg",
                fullWidth: 834,
                fullHeight: 395,
                aspectRatio: undefined
              }}
            />

            <div
              data-plasmic-name={"frame92"}
              data-plasmic-override={overrides.frame92}
              className={classNames(projectcss.all, sty.frame92)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___8ZQZh
                )}
              >
                {
                  "\u0412\u0456\u0442\u0430\u0435\u043c \u045e \u043f\u0430\u0440\u0430\u0444\u0456\u0456 \u0421\u0432. \u0411\u0430\u0440\u0442\u0430\u043b\u0430\u043c\u0435\u044f"
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nSQ
                )}
              >
                {
                  "\u041a\u0430\u0441\u0446\u0451\u043b \u0441\u0432\u044f\u0442\u043e\u0433\u0430 \u0411\u0430\u0440\u0442\u0430\u043b\u0430\u043c\u0435\u044f \u045e \u0412\u0456\u043b\u044c\u043d\u0456\u00a0\u2014 \u0433\u044d\u0442\u0430 \u043c\u0435\u0441\u0446\u0430 \u043c\u0430\u043b\u0456\u0442\u0432\u044b \u0456 \u0441\u0443\u0441\u0442\u0440\u044d\u0447\u044b, \u0434\u0437\u0435 \u0437\u0431\u0456\u0440\u0430\u0435\u0446\u0446\u0430 \u0431\u0435\u043b\u0430\u0440\u0443\u0441\u043a\u0430\u044f \u0441\u0443\u043f\u043e\u043b\u044c\u043d\u0430\u0441\u0446\u044c. \u0410\u0441\u0430\u0431\u043b\u0456\u0432\u0430\u0441\u0446\u044c \u043a\u0430\u0441\u0446\u0451\u043b\u0430 \u045e \u0442\u044b\u043c, \u0448\u0442\u043e\u00a0\u045e\u0441\u0435 \u043d\u0430\u0431\u0430\u0436\u044d\u043d\u0441\u0442\u0432\u044b \u0442\u0443\u0442 \u0430\u0434\u0431\u044b\u0432\u0430\u044e\u0446\u0446\u0430 \u0432\u044b\u043a\u043b\u044e\u0447\u043d\u0430 \u043d\u0430 \u0431\u0435\u043b\u0430\u0440\u0443\u0441\u043a\u0430\u0439 \u043c\u043e\u0432\u0435. \u0410\u043f\u0435\u043a\u0443 \u043d\u0430\u0434 \u043a\u0430\u0441\u0446\u0451\u043b\u0430\u043c \u043d\u044f\u0441\u0443\u0446\u044c \u0431\u0440\u0430\u0442\u044b \u0437 \u0411\u0435\u043b\u0430\u0440\u0443\u0441\u043a\u0430\u0439 \u041a\u0443\u0441\u0442\u043e\u0434\u044b\u0456 \u041e\u0440\u0434\u044d\u043d\u0430 \u041a\u0430\u043f\u0443\u0446\u044b\u043d\u0430\u045e."
                }
              </div>
            </div>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__eByA)}
              displayHeight={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "322px"
                  : "auto"
              }
              displayMaxHeight={"none"}
              displayMaxWidth={"none"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "541px"
                  : "480px"
              }
              loading={"lazy"}
              src={{
                src: "/plasmic/baltramiejus/images/image11.svg",
                fullWidth: 461,
                fullHeight: 314,
                aspectRatio: undefined
              }}
            />

            {(
              hasVariant(globalVariants, "screen", "mobileOnly") ? true : false
            ) ? (
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___5E2Mf)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "322px"
                    : "auto"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "auto"
                    : "480px"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/baltramiejus/images/image11.svg",
                  fullWidth: 461,
                  fullHeight: 314,
                  aspectRatio: undefined
                }}
              />
            ) : null}
          </div>
          <div
            className={classNames(
              projectcss.all,
              sty.freeBox__qD4Ux,
              "pattern-w-bg"
            )}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__oErso)}
            displayHeight={"100vh"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"100vw"}
            loading={"lazy"}
            src={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? {
                    src: "/plasmic/baltramiejus/images/image10.png",
                    fullWidth: 780,
                    fullHeight: 1292,
                    aspectRatio: undefined
                  }
                : {
                    src: "/plasmic/baltramiejus/images/image4.png",
                    fullWidth: 2560,
                    fullHeight: 1600,
                    aspectRatio: undefined
                  }
            }
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "link", "frame92"],
  link: ["link"],
  frame92: ["frame92"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  link: "a";
  frame92: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHome__VariantsArgs;
    args?: PlasmicHome__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHome__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHome__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHome__ArgProps,
          internalVariantPropNames: PlasmicHome__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),
    frame92: makeNodeComponent("frame92"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
